modLoader = "javafml"
loaderVersion = "[32,)"
license = "LGPLv3"

[[mods]]
modId = "minihud"
version = "${version}"
displayName = "MiniHUD-Forge"
displayURL="https://github.com/ThinkingStudios/MiniHUD-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
MiniHUD unofficial forge port.

Configurable "mini-F3" info lines, and various overlay renderers.
'''

[[dependencies.minihud]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minihud]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minihud]]
modId = "malilib"
mandatory = true
versionRange = "[0.1.0,)"
ordering = "NONE"
side = "BOTH"