modLoader = "javafml"
loaderVersion = "[38,)"
license = "LGPLv3"

[[mods]]
modId = "minihud"
version = "${version}"
displayName = "MiniHUD-Forge"
displayURL="https://github.com/ThinkingStudios/MiniHUD-Forge" #optional
logoFile="assets/minihud/icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
MiniHUD unofficial forge port.

Configurable "mini-F3" info lines, and various overlay renderers.
'''

[[dependencies.minihud]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minihud]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minihud]]
modId = "malilib"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
